/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TEST;

import BEAN_LIST_DATA.LDLigne;
import BEAN_LIST_DATA.LDListener;
import BEAN_LIST_DATA.LDModele;
import BEAN_LIST_DATA.LDTable;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author user
 * 
 */


public class Principal extends javax.swing.JFrame {
    
    public final ImageIcon Infos_02 = new javax.swing.ImageIcon(getClass().getResource("/IMG/Infos02.png"));
    public LDTable table = null;
    public LDModele model;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public void construireListe() {
        //RAS un très petit test
        table = new LDTable(scrollListe, new LDListener() {
            @Override
            public void OnActualiseBarreOutilsEtMenuContextuel(LDModele model) {
                //System.out.println("OnActualiseBarreOutilsEtMenuContextuel");
            }

            @Override
            public void OnInitialiseBarreOutilsEtMenuContextuel(LDModele model) {
                //System.out.println("OnInitialiseBarreOutilsEtMenuContextuel");
            }

            @Override
            public void OnAfficheMenuContextuel(Component support, int x, int y) {
                //System.out.println("OnAfficheMenuContextuel");
            }

            @Override
            public void OnConstruitLigneListe(LDModele model, LDLigne ligne, JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                //Si le model est un model Produit
                if (model instanceof ModelProduit) {
                    Produit produit = (Produit) value;
                    if (produit != null) {
                        ligne.setIcone((Infos_02), null);
                        String info01 = produit.getNom();
                        String info02 = produit.getDescription();
                        String info03 = "Enregistré en : " + produit.getDateEnreg() + " par " + produit.getNomUtilisateur();
                        ligne.setProprietes(info01, info02, info03);
                    }
                }
            }
        });
    }
    
    public void construireRubriqueProduit(){
        TabListe.addTab("Liste", scrollListe);
        
        model = new ModelProduit(tabDetails, scrollDetails, Produit.class, ecran, btback, btnext, Infos_02, TabListe, Infos_02, TabProprietes, champRechRapide, false, "LISTE DE PRODUIT", Infos_02, Infos_02);
        model.setCritere(1, "");
        model.actualiser();
        table.construire(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabListe = new javax.swing.JTabbedPane();
        scrollListe = new javax.swing.JScrollPane();
        TabProprietes = new javax.swing.JTabbedPane();
        scrollProprietes = new javax.swing.JScrollPane();
        tabDetails = new javax.swing.JTabbedPane();
        scrollDetails = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ecran = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        btnext = new javax.swing.JButton();
        champRechRapide = new UI.JS2bTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabListe.addTab("Liste", scrollListe);

        TabProprietes.addTab("Proprietés", scrollProprietes);

        tabDetails.addTab("Détails", scrollDetails);

        jButton1.setText("Charger");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Vider");
        jButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton2ItemStateChanged(evt);
            }
        });

        ecran.setText("Prêt.");

        btback.setText("Back");
        btback.setEnabled(false);
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btnext.setText("Next");
        btnext.setEnabled(false);
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        champRechRapide.setText("jS2bTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabListe)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ecran, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnext, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(champRechRapide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabProprietes, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabProprietes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(tabDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champRechRapide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabListe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ecran)
                    .addComponent(btnext)
                    .addComponent(btback))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        construireListe();
        construireRubriqueProduit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton2ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ItemStateChanged

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        // TODO add your handling code here:
        model.pagePrecendente(champRechRapide.getText().trim());
    }//GEN-LAST:event_btbackActionPerformed

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        model.pageSuivante(champRechRapide.getText().trim());
    }//GEN-LAST:event_btnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabListe;
    private javax.swing.JTabbedPane TabProprietes;
    private javax.swing.JButton btback;
    private javax.swing.JButton btnext;
    private UI.JS2bTextField champRechRapide;
    private javax.swing.JLabel ecran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane scrollDetails;
    private javax.swing.JScrollPane scrollListe;
    private javax.swing.JScrollPane scrollProprietes;
    private javax.swing.JTabbedPane tabDetails;
    // End of variables declaration//GEN-END:variables
}
