/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BEAN_LIST_DATA;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Gateway
 */
public class LDLigne extends javax.swing.JPanel {

    /**
     * Creates new form PanelEleve
     */
    private ImageIcon GrandeIcone;
    private LDCouleurs lDCouleurs;

    public LDLigne() {
        initComponents();
        viderTextes();
    }

    public void setIcone(ImageIcon GrandeIcone, LDCouleurs lDCouleurs) {
        this.GrandeIcone = GrandeIcone;
        setIconeGrand(GrandeIcone);
        if (lDCouleurs != null) {
            this.lDCouleurs = lDCouleurs;
        } else {
            this.lDCouleurs = new LDCouleurs();
        }
    }

    public void setTitrePanel(String titre, Color couleur) {
        this.titre.setText("--------------- [ " + titre + " ] ---------------");
        this.titre.setForeground(couleur);
    }

    public void viderTextes() {
        //vide les proprietes
        setProprietes("", "", "");
    }

    public void sentirSelection(boolean isSelected, int row) {
        if (isSelected == true) {
            this.setTitrePanel("Enregistrement n°" + (row + 1), Color.WHITE);
            this.setCouleurs(lDCouleurs.arriereSelection, lDCouleurs.avantSelection);
        } else {
            this.setTitrePanel("Enregistrement n°" + (row + 1), Color.black);
            if ((row % 2) == 0) {
                this.setCouleurs(lDCouleurs.arriereNormal, lDCouleurs.avantNormal);
            } else {
                this.setCouleurs(LDCouleurs.COULEUR_BLANCHE, lDCouleurs.avantNormal);
            }
        }
    }

    public ImageIcon getGrandeIcone() {
        return GrandeIcone;
    }

    public void setGrandeIcone(ImageIcon GrandeIcone) {
        this.GrandeIcone = GrandeIcone;
    }

    public void setProprietes(String info01, String info02, String info03) {
        if (info01.trim().length() != 0) {
            this.info01.setText(info01);
            this.info01.setVisible(true);
        } else {
            this.info01.setVisible(false);
        }
        if (info02.trim().length() != 0) {
            this.info02.setText(info02);
            this.info02.setVisible(true);
        } else {
            this.info02.setVisible(false);
        }
        if (info03.trim().length() != 0) {
            this.info03.setText(info03);
            this.info03.setVisible(true);
        } else {
            this.info03.setVisible(false);
        }
    }

    public void setCouleurs(Color backColor, Color frontColor) {
        this.setBackground(backColor);
        info01.setForeground(frontColor);
        info02.setForeground(frontColor);
        info03.setForeground(frontColor);
    }

    private void setIconeGrand(ImageIcon icone) {
        photo.setIcon(icone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        info01 = new javax.swing.JLabel();
        info02 = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        info03 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        photo.setBackground(new java.awt.Color(0, 0, 0));
        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Infos02.png"))); // NOI18N
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));

        info01.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        info01.setText("NOM DE L'ENREGISTREMENT");

        info02.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        info02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        info02.setText("AUTRE INFORMATION PERTINENTE");

        titre.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("-------------------[ Enregistrement n°01]--------------------");
        titre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        info03.setFont(new java.awt.Font("Cambria", 2, 11)); // NOI18N
        info03.setForeground(new java.awt.Color(51, 51, 51));
        info03.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        info03.setText("Dates et autres infos liées à qui l'a crée et dans quelle station");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photo)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titre)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(info01, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(info02)
                        .addGap(1, 1, 1)
                        .addComponent(info03))
                    .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel info01;
    public javax.swing.JLabel info02;
    public javax.swing.JLabel info03;
    public javax.swing.JLabel photo;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
